version: '3'

services:

  back-end:
    image: pfbarbosa/back-end
    restart: always
    entrypoint: dockerize -wait tcp://my-mysql:3306 -timeout 40s java -jar /opt/deploy/listmod.jar
    networks: 
      - my_mysql_backend
      - my_backend_frontend
    tty: true
    ports:
      - "8081:8080"
    depends_on: 
      - my-mysql  

  my-mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d 
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    ports:
      - "3306:3306"   
    networks: 
      - my_mysql_backend

  front-end:
    image: pfbarbosa/front-end
    restart: always
    entrypoint: dockerize -wait http://back-end:8080/modulos -timeout 40s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - "8000:80"
    depends_on: 
      - back-end
    networks: 
      - my_backend_frontend
  
networks: 
  my_mysql_backend:
    driver: bridge
  my_backend_frontend:
    driver: bridge
